package net.jakedot.jourwigo;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public final class CartridgeTemplateWriter {

    private CartridgeTemplateWriter() {
        // utility class
    }

    public static void writeLuaTemplate(Path path,
                                        String name,
                                        String author,
                                        String version,
                                        String description,
                                        double latitude,
                                        double longitude,
                                        double altitude) throws IOException {
        Files.writeString(path, buildLuaTemplate(name, author, version, description, latitude, longitude, altitude),
            StandardCharsets.UTF_8);
    }

    static String buildLuaTemplate(String name,
                                   String author,
                                   String version,
                                   String description,
                                   double latitude,
                                   double longitude,
                                   double altitude) {
        return "-- Urwigo-style cartridge template generated by jourwigo\n"
            + "Cartridge = Wherigo.ZCartridge()\n"
            + "Cartridge.Name = \"" + escapeLua(name) + "\"\n"
            + "Cartridge.Description = \"" + escapeLua(description) + "\"\n"
            + "Cartridge.Activity = \"TourGuide\"\n"
            + "Cartridge.StartingLocationDescription = \"Start\"\n"
            + "Cartridge.StartingLocation = Wherigo.ZonePoint(" + latitude + ", " + longitude + ", " + altitude + ")\n"
            + "Cartridge.Version = \"" + escapeLua(version) + "\"\n"
            + "Cartridge.Author = \"" + escapeLua(author) + "\"\n"
            + "\n"
            + "function OnStart()\n"
            + "    Wherigo.MessageBox({Text = \"Welcome to " + escapeLua(name) + "\"})\n"
            + "end\n";
    }

    private static String escapeLua(String value) {
        if (value == null) {
            return "";
        }
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n");
    }
}
